CXX = em++
CXXFLAGS = -g  --preload-file res --use-preload-plugins -Iinclude -std=c++14 -Istb

OBJS = src/CGame.o  src/CGameSnapshot.o SDLVersion/main.o SDLVersion/CSDLRenderer.o src/CRenderer.o src/Common.o src/NativeBitmap.o src/LoadPNG.o

TARGET = game.html

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(CXXFLAGS)

all:   $(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
	rm game.data
	rm game.js	